import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";

import clsx from "clsx";

import { Banner } from "@/components/banner";

import "./globals.css";

const dmSans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Saas Landing Page | Pedro Galembeck",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(dmSans.className, "antialiased")}>
        <Banner />
        {children}
      </body>
    </html>
  );
}
